/**
 * src/commands/handoff.ts — Renders handoff.md for AI agents
 */

import type { PlanContext } from "../contracts/chunked-generation";
import type { IngestRunArtifact } from "../ingestion/types";

export interface HandoffOptions {
  ownerRepo: string;
  slug: string;
  artifactPath: string;
  planContextPath: string;
  artifact: IngestRunArtifact;
  planContext: PlanContext;
  /** Override specific step statuses */
  stepOverrides?: Partial<Record<string, "DONE" | "PENDING" | "SKIPPED">>;
  /** Section IDs already persisted (for resume) */
  persistedSections?: string[];
}

export function renderHandoff(opts: HandoffOptions): string {
  const {
    ownerRepo,
    slug,
    artifactPath,
    planContextPath,
    artifact,
    planContext: ctx,
    stepOverrides,
    persistedSections,
  } = opts;

  const step = (name: string, fallback: "DONE" | "PENDING") =>
    stepOverrides?.[name] ?? fallback;

  const persistedSet = new Set(persistedSections ?? []);

  const sectionPlanPath = `devport-output/workspace/${slug}-section-plan.json`;
  const profileLines = [
    `- **Repo**: ${ownerRepo}`,
    `- **Commit**: ${artifact.commit_sha.slice(0, 7)}`,
    `- **Language**: ${ctx.profile.primaryLanguage}`,
    `- **Type**: ${ctx.profile.projectType}`,
    `- **Domain**: ${ctx.profile.domainHint}`,
    `- **Files scanned**: ${artifact.files_scanned.toLocaleString("en-US")}`,
    `- **Snapshot**: ${artifact.snapshot_path}`,
  ];

  const keyPathsList = ctx.keyPaths
    .slice(0, 20)
    .map((p) => `  - \`${p}\``)
    .join("\n");

  const sectionExample = JSON.stringify(
    {
      sectionId: "sec-1",
      titleKo: "프로젝트 개요 및 아키텍처",
      summaryKo: "이 섹션에서는 프로젝트의 목적과 전체 구조를 설명합니다.",
      sourcePaths: ["README.md", "src/main.ts"],
      subsections: [
        {
          subsectionId: "sub-1-1",
          titleKo: "프로젝트 소개",
          bodyKo: "(3000자 이상의 한국어 설명...)",
          sourcePaths: ["README.md"],
        },
      ],
    },
    null,
    2,
  );

  const lines: string[] = [
    `# Handoff: ${ownerRepo}`,
    "",
    "This file was generated by `portki`. Follow the steps below to complete the wiki generation.",
    "",
    "## Pipeline Status",
    "",
    `| Step | Status |`,
    `|------|--------|`,
    `| ingest | ${step("ingest", "DONE")} |`,
    `| plan-sections | ${step("plan-sections", "DONE")} |`,
    `| write section-plan.json | ${step("write-plan", "PENDING")} |`,
    `| validate-plan | ${step("validate-plan", "PENDING")} |`,
    `| write & persist sections | ${step("persist-sections", "PENDING")} |`,
    `| finalize | ${step("finalize", "PENDING")} |`,
    "",
    "## Repo Profile",
    "",
    ...profileLines,
    "",
    "## Key Paths to Read",
    "",
    keyPathsList,
    "",
    "## Artifact Files",
    "",
    `- Artifact: \`${artifactPath}\``,
    `- Plan context: \`${planContextPath}\``,
    `- Section plan (you write this): \`${sectionPlanPath}\``,
    "",
    "## Steps",
    "",
    "### Step 1: Read the plan context",
    "",
    `Read \`${planContextPath}\` to understand the repo structure, profile, and constraints.`,
    `Also read the README and key source files under \`${artifact.snapshot_path}\`.`,
    "",
    "### Step 2: Write section-plan.json",
    "",
    `Create \`${sectionPlanPath}\` with 4-6 sections. Each section needs:`,
    "- `sectionId`: sec-1, sec-2, ...",
    "- `titleKo`: Korean title (3+ chars)",
    "- `summaryKo`: Korean summary (10+ chars)",
    "- `focusPaths`: real paths from the snapshot",
    "- `subsections`: array of 3+ subsections with subsectionId, titleKo, objectiveKo, targetEvidenceKinds, targetCharacterCount",
    "",
    "### Step 3: Validate the plan",
    "",
    "```bash",
    `portki validate-plan --input ${sectionPlanPath} --context ${planContextPath} --out ${sectionPlanPath}`,
    "```",
    "",
    "### Step 4: Write and persist each section",
    "",
    "For each section in the plan:",
    "",
    "1. Read the focus files listed in the section plan",
    "2. Write a section output JSON file:",
    "",
    "```json",
    sectionExample,
    "```",
    "",
    "3. Persist it:",
    "",
    "```bash",
    `portki persist-section --plan ${sectionPlanPath} --section sec-N --input devport-output/workspace/${slug}-section-N-output.json`,
    "```",
    "",
  ];

  // Show per-section status if resuming
  if (persistedSections && persistedSections.length > 0) {
    lines.push("**Section progress:**", "");
    for (const secId of persistedSections) {
      lines.push(`- [x] ${secId} (persisted)`);
    }
    lines.push("");
  }

  lines.push(
    "### Step 5: Finalize",
    "",
    "```bash",
    `portki finalize --plan ${sectionPlanPath} --advance_baseline`,
    "```",
    "",
    `Output will be written to \`devport-output/wiki/${ownerRepo}/\`.`,
    "",
    "## Writing Rules",
    "",
    "- All Korean prose must use formal `합니다` style",
    "- Each `bodyKo` must be at least 3,000 characters",
    "- Include at least one Mermaid architecture block across all sections",
    "- `sourcePaths` must be real snapshot paths",
    "- `sub-1-1` is the project introduction summary (purpose, problem space, getting-started, section map)",
    "- Code call-flow analysis should begin in `sub-1-2` or later",
    "- Do not use repetitive filler blocks",
    "",
  );

  return lines.join("\n");
}
